using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SlotSmart.Domain.Common;

namespace SlotSmart.Infrastructure.Persistence.Configurations;

/// <summary>
/// Base EF Core configuration that wires the **dual-key identity pattern** (ADR-007 /
/// docs/plan/00-architecture/entity-identity.md §2) for every entity stored in
/// <see cref="SlotSmartDbContext"/>.
/// </summary>
/// <remarks>
/// Concrete configurations inherit and call <c>base.Configure(builder)</c> first:
/// <code>
/// public sealed class MemberConfiguration : EntityConfiguration&lt;Member&gt;
/// {
///     public override void Configure(EntityTypeBuilder&lt;Member&gt; builder)
///     {
///         base.Configure(builder);
///         builder.ToTable("Members");
///         // entity-specific mapping...
///     }
/// }
/// </code>
/// An architecture test (<c>EntityConfigurationDerivationTests</c>) asserts that every
/// <see cref="IEntityTypeConfiguration{TEntity}"/> implementer in this assembly derives from
/// this base — preventing accidental config classes that bypass the surrogate-PK wiring.
/// </remarks>
/// <typeparam name="TEntity">A persistent entity inheriting from <see cref="Entity"/>.</typeparam>
public abstract class EntityConfiguration<TEntity> : IEntityTypeConfiguration<TEntity>
    where TEntity : Entity
{
    /// <summary>The shadow-property name of the surrogate primary key.</summary>
    public const string SurrogateIdShadowProperty = "Id";

    public virtual void Configure(EntityTypeBuilder<TEntity> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        // Hidden surrogate primary key — added as an EF Core SHADOW property.
        // bigint, IDENTITY (SQL Server) / GENERATED BY DEFAULT AS IDENTITY (Postgres).
        builder.Property<long>(SurrogateIdShadowProperty)
               .ValueGeneratedOnAdd()
               .UseIdentityColumn();

        builder.HasKey(SurrogateIdShadowProperty);

        // Public domain identifier — UUIDv7. Server-generated by the entity factory; never updated.
        builder.Property(e => e.EntityId)
               .ValueGeneratedNever()
               .IsRequired();

        // Unique index on the public id (also used as the join target for FKs that
        // want to reference by public id; see entity-identity.md §5 option B).
        builder.HasIndex(e => e.EntityId).IsUnique();
    }
}
